(function($){Drupal.behaviors.betterExposedFilters={attach:function(context){$('.bef-tree input[type=checkbox], .bef-checkboxes input[type=checkbox]').change(function(){_bef_highlight(this,context);}).filter(':checked').closest('.form-item',context).addClass('highlight');}};Drupal.behaviors.betterExposedFiltersSelectAllNone={attach:function(context){var selected=$('.form-checkboxes.bef-select-all-none:not(.bef-processed)');if(selected.length){var selAll=Drupal.t('Select All');var selNone=Drupal.t('Select None');var link=$('<a class="bef-toggle" href="#">'+ selAll+'</a>')
link.click(function(event){event.preventDefault();event.stopPropagation();if(selAll==$(this).text()){$(this).html(selNone).siblings('.bef-checkboxes, .bef-tree').find('.form-item input:checkbox').each(function(){$(this).attr('checked',true);_bef_highlight(this,context);}).end().find('input[type=checkbox]:first').change();}
else{$(this).html(selAll).siblings('.bef-checkboxes, .bef-tree').find('.form-item input:checkbox').each(function(){$(this).attr('checked',false);_bef_highlight(this,context);}).end().find('input[type=checkbox]:first').change();}});selected.addClass('bef-processed').each(function(index){var newLink=link.clone(true);newLink.insertBefore($('.bef-checkboxes, .bef-tree',this));if($('input:checkbox:checked',this).length==$('input:checkbox',this).length){newLink.click();}});}
var befSettings=Drupal.settings.better_exposed_filters;if(befSettings&&befSettings.datepicker&&befSettings.datepicker_options&&$.fn.datepicker){var opt=befSettings.datepicker_options.dateformat?{dateFormat:befSettings.datepicker_options.dateformat}:{};$('.bef-datepicker').datepicker(opt);}}};Drupal.behaviors.betterExposedFiltersAllNoneNested={attach:function(context,settings){$('.form-checkboxes.bef-select-all-none-nested li').has('ul').once('bef-all-none-nested',function(){$(this).find('input.form-checkboxes:first').click(function(){$(this).parents('li:first').find('ul input.form-checkboxes').attr('checked',$(this).attr('checked'));}).end().find('ul input.form-checkboxes').click(function(){var checked=$(this).attr('checked');var ct=$(this).parents('ul:first').find('input.form-checkboxes:not(:checked)').size();if(!checked||!ct){$(this).parents('li:first').parents('li:first').find('input.form-checkboxes:first').attr('checked',checked);}});});}}
Drupal.behaviors.better_exposed_filters_slider={attach:function(context,settings){var befSettings=settings.better_exposed_filters;if(befSettings&&befSettings.slider&&befSettings.slider_options){$.each(befSettings.slider_options,function(i,sliderOptions){$("#"+ sliderOptions.viewId+" #edit-"+ sliderOptions.id+"-wrapper").once('slider-filter',function(){var $input=$(this).find('input[type=text]');if($input.length==2){var $min=$input.parent().find('input#edit-'+ sliderOptions.id+'-min'),$max=$input.parent().find('input#edit-'+ sliderOptions.id+'-max'),default_min,default_max;if(!$min.length||!$max.length){return;}
default_min=parseFloat(($min.val()=='')?sliderOptions.min:$min.val(),10);default_max=parseFloat(($max.val()=='')?sliderOptions.max:$max.val(),10);$min.val(default_min);$max.val(default_max);$min.parents('div.views-widget').after($('<div class="bef-slider"></div>').slider({range:true,min:parseFloat(sliderOptions.min,10),max:parseFloat(sliderOptions.max,10),step:parseFloat(sliderOptions.step,10),animate:sliderOptions.animate?sliderOptions.animate:false,orientation:sliderOptions.orientation,values:[default_min,default_max],slide:function(event,ui){$min.val(ui.values[0]);$max.val(ui.values[1]);},change:function(event,ui){$min.val(ui.values[0]);$max.val(ui.values[1]);},stop:function(event,ui){$(this).parents('form').find('.ctools-auto-submit-click').click();}}));$min.blur(function(){befUpdateSlider($(this),0,sliderOptions);});$max.blur(function(){befUpdateSlider($(this),1,sliderOptions);});}
else if($input.length==1){if($input.attr('id')!='edit-'+ sliderOptions.id){return;}
var default_value=parseFloat(($input.val()=='')?sliderOptions.min:$input.val(),10);$input.val(default_value);$input.parents('div.views-widget').after($('<div class="bef-slider"></div>').slider({min:parseFloat(sliderOptions.min,10),max:parseFloat(sliderOptions.max,10),step:parseFloat(sliderOptions.step,10),animate:sliderOptions.animate?sliderOptions.animate:false,orientation:sliderOptions.orientation,value:default_value,slide:function(event,ui){$input.val(ui.value);},change:function(event,ui){$input.val(ui.value);},stop:function(event,ui){$(this).parents('form').find('.ctools-auto-submit-click').click();}}));$input.blur(function(){befUpdateSlider($(this),null,sliderOptions);});}
else{return;}})});}}};function _bef_highlight(elem,context){$elem=$(elem,context);$elem.attr('checked')?$elem.closest('.form-item',context).addClass('highlight'):$elem.closest('.form-item',context).removeClass('highlight');}
function befUpdateSlider($el,valIndex,sliderOptions){var val=parseFloat($el.val(),10),currentMin=$el.parents('div.views-widget').next('.bef-slider').slider('values',0),currentMax=$el.parents('div.views-widget').next('.bef-slider').slider('values',1);if(valIndex!=null){if(valIndex==0&&val>currentMax){val=currentMax;}
if(valIndex==1&&val<currentMin){val=currentMin;}
if(isNaN(val)){val=$el.parents('div.views-widget').next('.bef-slider').slider('values',valIndex);}}
else{if(isNaN(val)){val=$el.parents('div.views-widget').next('.bef-slider').slider('value');}}
val=parseFloat(val,10);if(valIndex!=null){$el.parents('div.views-widget').next('.bef-slider').slider('values',valIndex,val);}
else{$el.parents('div.views-widget').next('.bef-slider').slider('value',val);}}})(jQuery);