(function($){Drupal.behaviors.facetapi={attach:function(context,settings){if(settings.facetapi){for(var index in settings.facetapi.facets){if(null!=settings.facetapi.facets[index].makeCheckboxes){Drupal.facetapi.makeCheckboxes(settings.facetapi.facets[index].id);}
if(null!=settings.facetapi.facets[index].limit){Drupal.facetapi.applyLimit(settings.facetapi.facets[index]);}}}}}
Drupal.facetapi={}
Drupal.facetapi.applyLimit=function(settings){if(settings.limit>0&&!$('ul#'+ settings.id).hasClass('facetapi-processed')){$('ul#'+ settings.id).addClass('facetapi-processed');var limit=settings.limit- 1;$('ul#'+ settings.id).find('li:gt('+ limit+')').hide();$('ul#'+ settings.id).filter(function(){return $(this).find('li').length>settings.limit;}).each(function(){$('<a href="#" class="facetapi-limit-link"></a>').text(Drupal.t(settings.showMoreText)).click(function(){if($(this).siblings().find('li:hidden').length>0){$(this).siblings().find('li:gt('+ limit+')').slideDown();$(this).addClass('open').text(Drupal.t(settings.showFewerText));}
else{$(this).siblings().find('li:gt('+ limit+')').slideUp();$(this).removeClass('open').text(Drupal.t(settings.showMoreText));}
return false;}).insertAfter($(this));});}}
Drupal.facetapi.Redirect=function(href){this.href=href;}
Drupal.facetapi.Redirect.prototype.gotoHref=function(){window.location.href=this.href;}
Drupal.facetapi.makeCheckboxes=function(facet_id){var $facet=$('#'+ facet_id),$links=$('a.facetapi-checkbox',$facet);$links.once('facetapi-makeCheckbox').each(Drupal.facetapi.makeCheckbox);$links.once('facetapi-disableClick').click(function(e){Drupal.facetapi.disableFacet($facet);});}
Drupal.facetapi.disableFacet=function($facet){$facet.addClass('facetapi-disabled');$('a.facetapi-checkbox').click(Drupal.facetapi.preventDefault);$('input.facetapi-checkbox',$facet).attr('disabled',true);}
Drupal.facetapi.preventDefault=function(e){e.preventDefault();}
Drupal.facetapi.makeCheckbox=function(){var $link=$(this),active=$link.hasClass('facetapi-active');if(!active&&!$link.hasClass('facetapi-inactive')){return;}
var id=this.id+'--checkbox',description=$link.find('.element-invisible').html(),label=$('<label class="element-invisible" for="'+ id+'">'+ description+'</label>'),checkbox=$('<input type="checkbox" class="facetapi-checkbox" id="'+ id+'" />'),href=$link.attr('href'),redirect=new Drupal.facetapi.Redirect(href);checkbox.click(function(e){Drupal.facetapi.disableFacet($link.parents('ul.facetapi-facetapi-checkbox-links'));redirect.gotoHref();});if(active){checkbox.attr('checked',true);$link.before(label).before(checkbox).hide();}
else{$link.before(label).before(checkbox);}}})(jQuery);